
name: build-examples

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      - 
        name: Build all example sketches (UNO)
        uses: pfeerick/arduino-builder-action@master
        with:
          board: "arduino:avr:uno"
         